### PR TITLE
Update .yarnrc.yml

### PR DESCRIPTION
**Pull request by belyrs**

### CODE REVIEW

**Comment by amarts** [comment]
I see changes which are already in there also here. Can you rebase (check git docs) to latest of the repo branch and send PR?

Ie, this PR, when checking on the `files` section should have just 1 file and 1 line change. Thats when this is ready to merge.

**Comment by amarts** [comment]
Also add 'Fixes: #33` in PR body (you can edit above). That way, the issue automatically closes. Also send this PR to `develop` branch also.

**Comment by belyrs** [comment]
Ok, I will do that

**Comment by amarts** [comment]
Due to another update I needed, added fix in .yarnrc in this branch. Will close it for now.

**Pull request closed without merging**
