### PR TITLE
stream.update() : implement methods to handle content update without changing identifier

### PR DESCRIPTION
**Pull request by belyrs**
Modified demo and added a file(updateDocument.ts) in the utils. 

Delegate prepares a new content in the demo and calls the updateStream method in the updateDocument.ts. updateStream method in turn calls the updateFromContent method in the Document.ts.

This PR has been initiated in response to the reviews of - https://github.com/dhiway/cord.js/pull/108.

### CODE REVIEW

**Review by amarts — COMMENTED** [review]
code changes LGTM.

Comment on git commit message.

I said I need notification on merge requiring a release, not in subject or body of commit message. 

Subject of commit/PR and body / description should **always** be about the changes done in PR. You can notify requirement of the release as a separate commit, or as a label.  Idea is,  a single developer doesn't decide when the project makes a release, but the changes requiring release should be tagged.

**Comment by amarts** [comment]
```
➤ YN0000: src/document/Document.ts(32,17): error TS6133: 'bool' is declared but its value is never read.
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
➤ YN0000: Failed with errors in 1m 39s
```

**Comment by belyrs** [comment]
> code changes LGTM.
> 
> Comment on git commit message.
> 
> I said I need notification on merge requiring a release, not in subject or body of commit message.
> 
> Subject of commit/PR and body / description should **always** be about the changes done in PR. You can notify requirement of the release as a separate commit, or as a label. Idea is, a single developer doesn't decide when the project makes a release, but the changes requiring release should be tagged.

Noted. Thank you

**Comment by belyrs** [comment]
> ```
> ➤ YN0000: src/document/Document.ts(32,17): error TS6133: 'bool' is declared but its value is never read.
> ➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
> ➤ YN0000: Failed with errors in 1m 39s
> ```

Resolved this

**Review by amarts — APPROVED** [review]
@smohan-dw have a look when you get a chance. Would like to take this in and make further changes on any feedback as a follow-up. 

Helps in getting few integrations complete soon.

**Pull request merged**
